### ISSUE TITLE
i want study this code

### ISSUE THREAD

**Issue by clowns123** [technikhil314/next-webrtc#2]
But I don't know the contents of the .env file.
I want to run your code.
Can you help me?

**Comment by technikhil314** [comment]
Sure. I you are ok we can hop onto a call and I can explain you how it works. @clowns123 I am in IST (GMT +5.30) timezone. What time suits you?

**Comment by clowns123** [comment]
I'd love to hear your explanation, too.
Unfortunately, I am not good at English.

Thank you for the contents of .env.

I joined a company that uses webRTC this time.
So your code was very helpful, thank you.

**Comment by technikhil314** [comment]
No worries. I'm glad its helpgul to you.
